### PR TITLE
Update scrawl-canvas library to v8.8.1

### PR DESCRIPTION
**Pull request by KaliedaRik**
Scrawl-canvas has been evolving a lot since it was last updated in the comparisons test. This PR brings the library used here in line with those latest developments.

### CODE REVIEW

**Comment by KaliedaRik** [comment]
Many thanks!

**Comment by mkalygin** [comment]
Thank you for your time, @KaliedaRik! 

It looks like the error comes from `scrawl.library` not being defined anymore (`scrawl.library.animation` fails).

**Comment by KaliedaRik** [comment]
Hi @gnykka @mkalygin - can I ask a question? When you merged the PR, did you then `install/rebuild` the site before deploying it?

The main breaking change in Scrawl-canvas v8.8.0 was to remove the library's default export, which is why line 2 changes from `import scrawl from "scrawl-canvas";` to `import * as scrawl from "scrawl-canvas";` - but if the `install/rebuild` step wasn't run then the site may be using the previous version.

**Comment by KaliedaRik** [comment]
Hi @gnykka @mkalygin - shall I assume this issue is not going to be fixed?

**Comment by mkalygin** [comment]
@KaliedaRik sorry, we haven't got a chance to take a look at it but it will be fixed this weekend.

**Comment by mkalygin** [comment]
@KaliedaRik the demo for Scrawl Canvas has been fixed:

https://benchmarks.slaylines.io/scrawl-canvas.html

**Comment by KaliedaRik** [comment]
@mkalygin - thank you - and so sorry that this turned out to be more work for you than I expected!

Whenever the issue of canvas libraries come up (eg on Reddit) I always post a link to this demo as it is such a useful resource. Now I can post the link without feeling embarrassed about my own library being broken in the demo.

Best wishes, Rik.

**Comment by mkalygin** [comment]
@KaliedaRik no worries, it wasn't that difficult to fix! I'm glad I could help, and thank you for sharing our work! 🙌

**Pull request merged**
